### PR TITLE
Update Project.toml

### PR DESCRIPTION
**Pull request by zsz00**

### CODE REVIEW

**Comment by nalimilan** [comment]
Indeed, as Chain is reexported then allowing a new version which is breaking requires tagging a breaking version of DataFramesMeta too. Better disallow 0.4 too, otherwise users can silently get a different API just because Chain changes version.

**Comment by pdeffebach** [comment]
Thanks! @zsz00 can you make these changes?

**Comment by pdeffebach** [comment]
yes please.

**Comment by zsz00** [comment]
Done

**Comment by zsz00** [comment]
can you realse a 0.12.0 ?

**Comment by pdeffebach** [comment]
Released! Thanks.

**Pull request merged**
