### PR TITLE
use `syms` instead of `^()`

### PR DESCRIPTION
**Pull request by pdeffebach**
Addresses #125

### CODE REVIEW

**Review by bkamins — APPROVED** [review]
Looks good. Can you just leave comments in the code in places that have to be cleaned up after deprecation?

**Comment by pdeffebach** [comment]
Thanks! 

Despite being a small PR, this is a big decision. I will ask on Slack how people feel.

**Comment by jkrumbiegel** [comment]
My first thought is, why `syms` if it's used to designate one Symbol? Maybe `sym` is better. Another idea would be `@sym` because macro symbols always signal nicely that something non-standard is going on, while a normal looking function could fly under the radar. My last idea now would be to use `esc` because I think that's a function usually only used within macros, therefore not likely to clash with anything, and I think it's very closely related to its macro use. Escape the symbol into the outer expression, instead of mangling it inside the macro

**Comment by jkrumbiegel** [comment]
I have seen you compared `syms` to the existing `cols` and I'd argue the same there. Why not `col` if we're talking about a single column specifier here?

**Comment by nalimilan** [comment]
I agree a function is clearer than `^`. But why use the plural here? `esc` is also an interesting possibility.

> I have seen you compared `syms` to the existing `cols` and I'd argue the same there. Why not `col` if we're talking about a single column specifier here?

Actually `syms` is almost the contrary of `cols` here since it means that the symbol should be used literally.

**Comment by pdeffebach** [comment]
Thanks for the feedback. I think we need to iterate on the design more. 

1. I called it `syms` because `cols` is plural. This would be more consistent. Given that `cols` only accepts a single column at the moment, arguably they should both be singular. But we should keep in mind #229, since we might eventually want `cols` to accept multiple columns eventually.  
2. `syms` is actually a bad name for this particular functionality. What `syms` *actually* does is protect the entire expression contained, so you can do 

```
@transform(df, x = syms([:a, :b])
```

or
 
```
@transform(df, x = syms(1 + 2 * 100))
```

in which case `syms` does nothing. 

I think this is a valid thing to be able to do, but I also think that, for the sake of the user, we could keep "protecting a `Symbol`" and "protecting an entire expression" separate.

**Comment by nalimilan** [comment]
Right. So maybe `esc` is better?

**Comment by pdeffebach** [comment]
Sure `esc` is good. 

It's not the most intuitive name but if you think it's consistent with it's usage in Base, it sounds good.

**Comment by EconometricsBySimulation** [comment]
I am not sure if this would cause a problem with macro coding but what about `x = $(:a)`. I think `$` is used consistently to tell the user that the block of code is looking outside of itself.

**Comment by knuesel** [comment]
`$` makes sense! It's very convenient (`x = $:a` should also work) and it's consistent with Base: the `@.` macro uses `$` to escape functions. From the documentation:

> If you want to avoid adding dots for selected function calls in `expr`, splice those function calls in with `$`. For example, `@. sqrt(abs($sort(x)))` is equivalent to `sqrt.(abs.(sort(x)))` (no dot for `sort`).

This is similar to how `$` would protect symbols from being "columnized".

**Comment by pdeffebach** [comment]
Hmmm... I dont know, `$` also seems like it could be a good replacement for `cols`. Like in a quoted expression

```
x = :hello
t = :($x = 4)
```

I'm partial to replacing `cols` with `$` because it will be used more frequently.

**Pull request closed without merging**
