### PR TITLE
add astable macro

### PR DESCRIPTION
**Pull request by pdeffebach**
Not yet ready for a review. 

To simulate `@t` from DataFrameMacros

```
julia> df = DataFrame(a = rand(5), b = rand(5));

julia> @transform df @astable begin 
           :x = :b
           $"hello" = :a
       end
5×4 DataFrame
 Row │ a         b         x         hello    
     │ Float64   Float64   Float64   Float64  
─────┼────────────────────────────────────────
   1 │ 0.495296  0.788492  0.788492  0.495296
   2 │ 0.935795  0.895012  0.895012  0.935795
   3 │ 0.340286  0.32458   0.32458   0.340286
   4 │ 0.911353  0.585055  0.585055  0.911353
   5 │ 0.74855   0.655892  0.655892  0.74855
```

### CODE REVIEW

**Comment by pdeffebach** [comment]
A note on the API: As you may know I also maintain [AddToField.jl](https://github.com/pdeffebach/AddToField.jl/) with syntax

```
@addnt begin 
    @add x = 1
    @add y = 5
end
```

To make the named tuple `(x = 1, y = 5)`. 

This functionality is similar, but a bit more DataFrames specific. It allows for consistency by keeping `:x` and `$x` referring to columns in the DataFrame. We can't do that in an external macro because we need to treat the column identifiers on the LHS in a special way.

**Comment by pdeffebach** [comment]
Okay I'm thinking I will need to port over more of DataFrameMacros.jl's parsing code, in particular the stuff that uses `MacroTools.postwalk`. I will think more about this tomorrow.

**Comment by bkamins** [comment]
Thank you for working on this!

**Comment by pdeffebach** [comment]
Closed in favor of #298

**Pull request closed without merging**
