### PR TITLE
Remove methods not belonging to DataFramesMeta.jl

### PR DESCRIPTION
**Pull request by bkamins**
This should resolve https://github.com/JuliaData/DataFramesMeta.jl/issues/121.

In general I would also remove `DataFrame(::GroupedDataFrame)` method. If you feel it is useful let us add it to DataFrames.jl.

@nalimilan - any opinion?

### CODE REVIEW

**Comment by bkamins** [comment]
sorry for the larger PR than indented my editor automatically strips trailing spaces from the code.

**Comment by bkamins** [comment]
and in general if we want to keep DataFramesMeta.jl up to date with DataFrames.jl I think we should move it somewhat "closer" to it as I am always unsure if DataFramesMeta.jl will still work after we change DataFrames.jl. @nalimilan: do you have an opinion what should be our policy?

**Comment by nalimilan** [comment]
I agree we should remove that method from here. It could make sense to have it in DataFrames. Is it defined for internal use or for convenience? If the latter, better deprecate it now in favor of `combine`, so that we can add it later in DataFrames if we want.

**Comment by bkamins** [comment]
It is defined for convenience. But I would decide if we want it in DataFrames.jl. If yes then we can simply move it there and synchronize the releases without deprecation period.

So the question is if we want do define it in DataFrames.jl - I would say yes, as I do not see the reason why we should not do it (but I guess it might be related to your general design ideas in https://github.com/JuliaData/DataFrames.jl/issues/1256 so please decide).

**Comment by nalimilan** [comment]
OK, let's move it to DataFrames then.

**Comment by bkamins** [comment]
This should be merged only after https://github.com/JuliaData/DataFrames.jl/pull/1689 is merged and released.

**Comment by bkamins** [comment]
I will still need to test it after we release DataFrames.jl

**Pull request merged**
