### PR TITLE
delete @select! reference

### PR DESCRIPTION
**Pull request by pdeffebach**
In reference to #218. We shouldn't update the readme to discuss `@select!` and `@transform!` until we make a new release. 

I would rather wait for a new release until we have `@subset` and `@subset!` and maybe and `@orderby!`. 

cc @nalimilan

### CODE REVIEW

**Review by bkamins — APPROVED** [review]
Though I would remove the documentation from README.md entirely

**Comment by pdeffebach** [comment]
I think the best solution is to take the current version of the readme and make it the docstring for the module. Then we can add to that as needed. Then before releases we just copy over the docstring as is to the actual readme.

**Comment by nalimilan** [comment]
There's already a list of provided function in the homepage of the Documenter manual. So why not remove the list from the README completely? I don't think it's standard to have a docstring for a module listing all functions it exports: Documenter does that automatically already so adding a manual list which is likely to get outdated isn't great.

**Comment by pdeffebach** [comment]
Okay, updated to delete the list of macros entirely. With an approval I will merge.

**Review by nalimilan — APPROVED** [review]

**Pull request merged**
