### PR TITLE
Allow for Between, Not, All, Cols in `@select`

### PR DESCRIPTION
**Pull request by pdeffebach**

### CODE REVIEW

**Comment by pdeffebach** [comment]
Tests fail because of `@linq`. This means we finally get to deprecate `@linq` completely and remove it!

**Comment by bkamins** [comment]
I would remove `@linq`.

**Review by bkamins — APPROVED** [review]
Maybe add a comment that anything within these calls is left untouched. What I mean is that `Cols(:A)` does not do re-interpretation of `:A`.

**Comment by pdeffebach** [comment]
Doctest failures are fixed in #367 so I'm comfortable merging.

**Comment by pdeffebach** [comment]
Actually, I'm going to change the implementation slightly so `@groupby` works better.

**Comment by pdeffebach** [comment]
@bkamins okay to merge? This is a pretty simple PR. Will open a new PR for `@groupby` using this shortly.

**Comment by bkamins** [comment]
Looks good

**Pull request merged**
