### PR TITLE
Add exclamations

### LINKED ISSUE #293: `@rtransform!` and `@rselect!` aren't actually modifying dataframe
```
julia> df = DataFrame(a = 1, b = 2)
1×2 DataFrame
 Row │ a      b     
     │ Int64  Int64 
─────┼──────────────
   1 │     1      2

julia> xx = ["a", "b"];

julia> for x in xx
           @rtransform! df $x = $x + 100
       end

julia> df
1×2 DataFrame
 Row │ a      b     
     │ Int64  Int64 
─────┼──────────────
   1 │     1      2
```

### PR DESCRIPTION
**Pull request by pdeffebach**
Fixes #293 

@bkamins @nalimilan please review and merge!

Tests pass. This is a major oversight and needs to be fixed quickly. 

Thank you!

### CODE REVIEW

**Review by bkamins — APPROVED** [review]
I am approving to speed up process.
You need to bump the version and update the docs before merging (I will do this if you do not do this soon).

**Comment by bkamins** [comment]
There is some issue with Documenter in CI. But when I run it locally it works.

**Comment by pdeffebach** [comment]
If I merge and the build fails, will it use the old version of the docs?

**Comment by bkamins** [comment]
I think so. Let us try to make Documenter work for a bit more 😄.

**Comment by pdeffebach** [comment]
Jacob's snippet worked. 

Thanks for the fast turnaround! Registration [here](https://github.com/JuliaRegistries/General/pull/44464).

**Pull request merged**
