### PR TITLE
Host documentation on GH Actions

### PR DESCRIPTION
**Pull request by pdeffebach**

### CODE REVIEW

**Comment by pdeffebach** [comment]
Given that we already have a `DOCUMENTER_KEY` set up, I think this should work when merged into master? 

I'm not sure, to be honest.

**Comment by pdeffebach** [comment]
cc @nalimilan or @quinnj, or anyone who knows how github actions work. 

This PR is a bit time-sensitive, I guess since people are already asking why the docs are down.

**Review by nalimilan — APPROVED** [review]
Look reasonable. I don't know for sure, but if you merge you'll find out. :-)

**Comment by nalimilan** [comment]
Also, I was suggesting to move all CI to GitHub since Travis doesn't work at all now.

**Comment by pdeffebach** [comment]
Yes, that is definitely the next step.

**Pull request merged**
